spring:
  application:
    name: Reshavalnik
  data:
    mongodb:
      uri: ${MONGO_URL}

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

openai:
  api:
    key: ${OPENAPI_KEY}
    url: https://api.openai.com

sentry:
  dsn: ${SENTRY_DNS}
  traces-sample-rate: 1.0

jwt:
  secret:
    key: reshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnikreshavalnik
    jwtExpirationMs: 155520000000